[project]
name = "ragsql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=2.3.0",
    "psycopg2-binary>=2.9.11",
    "pytest>=8.4.2",
    "requests>=2.32.5",
]
